server:
  port: 8080   # Port on which the application will run

spring:
  application:
    name: RESTAPIApplication   # Your app name

  datasource:
    url: jdbc:mysql://localhost:3306/myblog   # DB URL
    username: root
    password: 7@Nikhil
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # update | create | create-drop | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.nikhil: DEBUG   # Your package-specific logging

management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose all actuator endpoints (health, metrics, etc.)

